import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

import { Inter } from 'next/font/google' 
// const roboto = Roboto({
//   weight: ['400', '500', '700'],
//   subsets: ['latin'],
// })
const inter = Inter({
  weight:['400', '500', '700'],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Clock and md editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
